//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vega.USiteBuilder.VsIntegration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vega.USiteBuilder.VsIntegration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///         * Use DocumentTypeProperty attribute to specify which properties will be treated as
        ///         * a document type properties. Through this attribute you can also set various properties
        ///         * of a document type (e.g. Description, Mandatory, Tab etc...)
        ///         */.
        /// </summary>
        internal static string DocumentTypePropertyTip {
            get {
                return ResourceManager.GetString("DocumentTypePropertyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///     * Use DocumentType attribute to specify various document type properties as in the 
        ///     * following example:
        ///     * 
        ///     * [DocumentType(DefaultTemplate = typeof(Template1), AllowedChildNodeTypes = new Type[] { typeof(DocumentType1), typeof(DocumentType1)})]
        ///     * public class ...
        ///     */.
        /// </summary>
        internal static string DocumentTypeTip {
            get {
                return ResourceManager.GetString("DocumentTypeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///     * Wizard created this Template (masterpage) by subclassing Vega.USiteBuilder.TemplateBase.
        ///     * If you choose strongly typed template, you had to supply DocumentType that
        ///     * will be related with this masterpage. In that case you can access the current rendered
        ///     * content based on choosen DocumentType using this.CurrentContent.
        ///     * 
        ///     * NOTE: If this template is strongly typed with some document type, this template will be
        ///     * automatically added to AllowedTemplates li [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TemplateTip {
            get {
                return ResourceManager.GetString("TemplateTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///     * Wizard created this control by subclassing Vega.USiteBuilder.WebUserControlBase.
        ///     * If you choose strongly typed web user control, you had to supply DocumentType that
        ///     * will be related with this control. You can access the content based on choosen
        ///     * DocumentType with: this.Content. If you didn&apos;t set ContentNodeId property of this control
        ///     * than the current nodeid is used to get the content into the Content property of this control.
        ///     * 
        ///     * If you want to use  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebUserControlTip {
            get {
                return ResourceManager.GetString("WebUserControlTip", resourceCulture);
            }
        }
    }
}
